services:
  apiserver:
    build:
      context: .
      dockerfile: ./mods/apiserver/Dockerfile

  asterisk01:
    build:
      context: .
      dockerfile: ./asterisk/Dockerfile
    ports:
      - 6060:6060
      - 8088:8088

  asterisk02:
    ports:
      - 6161:6060
      - 8188:8088

  postgres:
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    ports:
      - 8282:8080

  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025
      - 1025:1025