services:
  apiserver:
    build:
      context: .
      dockerfile: ./mods/apiserver/Dockerfile

  routr:
    ports:
      - 51907:51907
      - 51908:51908
      - 5060:5060/udp
      - 5060-5063:5060-5063
    volumes:
      - ./etc/log4j2.yaml:/etc/routr/log4j2.yaml

  asterisk01:
    build:
      context: .
      dockerfile: ./asterisk/Dockerfile
    volumes:
      - ./etc/hello-world.sln16:/var/lib/asterisk/sounds/hello-world.sln16

  asterisk02:
    volumes:
      - ./etc/hello-world.sln16:/var/lib/asterisk/sounds/hello-world.sln16

  postgres:
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    ports:
      - 8282:8080

  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025
      - 1025:1025

  simplephone:
    image: psanders/simplephone:latest
    ports:
      - 8181:8080