services:
  apiserver:
    build:
      context: .
      dockerfile: ./mods/apiserver/Dockerfile
    volumes:
      - ./.keys:/opt/fonoster/keys
      - ./integrations.json:/opt/fonoster/integrations.json
    environment:
      ROUTR_API_ENDPOINT: ${ROUTR_API_ENDPOINT}

  routr:
    ports:
      - 51907:51907
      - 51908:51908
      - 5060:5060/udp
      - 5060-5063:5060-5063
    environment:
      # In development this environment variable points to an
      # address not accessible from the container. Therefore, we
      # need to manually point to the NAT's container address here.
      NATS_PUBLISHER_URL: nats://nats:4222
      CONSOLE_PUBLISHER_ENABLED: "true"
    volumes:
      - ./etc/log4j2.yaml:/etc/routr/log4j2.yaml

  asterisk01:
    build:
      context: .
      dockerfile: ./asterisk/Dockerfile
    ports:
      - 6060:6060
      - 8088:8088
    extra_hosts:
      apiserver: ${DOCKER_HOST_ADDRESS}

  postgres:
    ports:
      - 5432:5432

  influxdb:
    ports:
      - 8086:8086

  envoy:
    ports:
      - 8443:8443
    extra_hosts:
      apiserver: ${DOCKER_HOST_ADDRESS}
    environment:
      - loglevel=debug

  nats:
    ports:
      - 4222:4222

  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    ports:
      - 8282:8080

  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025
      - 1025:1025

  simplephone:
    image: psanders/simplephone:latest
    ports:
      - 8181:8080