name: test sdk install

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install and build the SDK with npm
        run: |
          npm install
          npm run build

      - name: Pack the SDK
        run: |
          npm pack
        working-directory: mods/sdk

  install-with-yarn:
    runs-on: ubuntu-latest
    needs: build

    strategy:
      matrix:
        node-version: [18, 20, 21, 22]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install the SDK with yarn
        run: |
          echo "Installing the SDK with yarn"
          # Verify that the tarball is downloaded
          ls -l
          mkdir new_project
          cd new_project
          yarn init -y
          yarn add ../mods/sdk/fonoster-*.tgz

  install-with-npm:
    runs-on: ubuntu-latest
    needs: build

    strategy:
      matrix:
        node-version: [18, 20, 21, 22]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install the SDK with npm
        run: |
          mkdir new_project
          cd new_project
          npm init -y
          npm install ../mods/sdk/fonoster-*.tgz